### ISSUE TITLE
map won't open

### ISSUE THREAD

**Issue by Ohsem-JacSparrow** [samedog/GVONavish#1]
i don't know why i can't open GVONavish map for the past 3 days. 
After double click on the GVONavish application, there is no response at all.
i'm using version 1.3.2.1

**Comment by samedog** [comment]
hi, what windows version are you using? are you opening it with administrative permissions?

**Comment by Ohsem-JacSparrow** [comment]
I'm using Windows 10 and what kinda permission that you mentioned?

**Comment by samedog** [comment]
i meant run as admin, anyways your issue is weird since I'm using the release .exe from 2016 on windows 11 so I really don't know what the issue could be

**Comment by Ohsem-JacSparrow** [comment]
The problem is nothing happens after i clicked on it. Only opens up an icon
at task bar below and nothing happens. Atleast we know what to solve if
there is a pop up but nothing pops up.

**Comment by samedog** [comment]
i'm gonna upload a new release rebased to windows 10, hope it works

**Comment by Ohsem-JacSparrow** [comment]
Awesome, thanks!
So do i need to delete  the file folder GVONavish - 1.3.2.1 ?

**Comment by samedog** [comment]
yes, this one should replace it instead

**Comment by Ohsem-JacSparrow** [comment]
Ok.. good to know

**Comment by samedog** [comment]
marking as closed

**Comment by Ohsem-JacSparrow** [comment]
i see there are 2 zip files: 32 bits and 64 bits. Which one should i click?

**Comment by Ohsem-JacSparrow** [comment]
i've downloaded the 64 bits and it is working again. thanks.

**Comment by Ohsem-JacSparrow** [comment]
today, it didn't work again then i re-do the unzip and i noticed this could
be the culprit. yesterday, i just run it without thinking much. i have
attached the screenshot.it's Window not letting it to open.

**Comment by samedog** [comment]
prefer the 32 bits one, sinsce the 64 needs more work to get all the features working again
